name: Deploy to GitHub Pages

# Run workflow on every push to main
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code from the main branch
    - uses: actions/checkout@v2

    # sets up .NET Core SDK 10.0.100
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.100

    # sets up python3
    # - name: installs python3
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.13' 

    # restores blazor wasm workloads
    # - name: Restore WASM workloads
    #   run: dotnet workload install wasm-

    # changes the base-image-path in CustomPage.razor from '/curriculum-vitae/' to '../curriculum-vitae/' to match base blazor template
    - name: Change base-image-path in CustomPage.razor from /images to /hc-dental-clinic/images
      run: sed -i 's|/images/|/hc-dental-clinic/images/|g' src/HcDentalClinic/Pages/LandingPage.razor

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core project
      run: dotnet publish -c Release -o release --nologo

    - name: Change image paths in release index.html to /hc-dental-clinic/images
      run: sed -i 's|/images/|/hc-dental-clinic/images/|g' release/wwwroot/index.html

    # changes the base-tag in index.html from '/' to 'hc-dental-clinic' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to hc-dental-clinic
      run: sed -i 's/<base href="\/" \/>/<base href="\/hc-dental-clinic\/" \/>/g' release/wwwroot/index.html

    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages not to treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot